### ISSUE TITLE
shadowsocks to M1

### ISSUE THREAD

**Issue by TangHengxuan** [cloverzrg/shadowsocks-docker#2]
大佬您好，我在最新版的shadowsocks下看到您对M1 series问题提供了自己的解决方案，我能私下请教下您该怎么去使用它吗？打扰得有些冒昧，抱歉

**Comment by cloverzrg** [comment]
https://github.com/cloverzrg/ShadowsocksX-NG/releases/tag/v1.9.6

**Comment by TangHengxuan** [comment]
> 

大佬，愚蠢地问一下，我是把三个文件下载好之后就能用吗，没有硬性要求source zip解压后文件和shadowsocks-NG放在一起哇？source code zip和tar.gz两个压缩包都是一样的？下载其中之一就好（我已经都下载并解压后猜测的）？
真的真的不好意思打扰您

**Comment by cloverzrg** [comment]
只需要第一个文件，解压就可以双击运行了， 可能会有安全提示或者需要特殊设置才能打开， 自己搜索下。 下面两个source code是源码， 不需要

**Comment by TangHengxuan** [comment]
完全OK了，谢谢大佬，感恩
